// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpflvukunwlzcxxpepxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZmx2dWt1bndsemN4eHBlcHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTcwNjUsImV4cCI6MjA2NjA5MzA2NX0.DfcZ29wJYZ1crgUePJ7w-Dyhb93JX2jW5FQo9QqmRRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);